services:
  pm.twig.cssversion:
    class: PM\Bundle\ToolBundle\Twig\CssVersionExtension
    tags:
      - { name: twig.extension }
  pm.twig.hash:
    class: PM\Bundle\ToolBundle\Twig\HashExtension
    tags:
      - { name: twig.extension }
  pm.twig.icon:
    class: PM\Bundle\ToolBundle\Twig\IconExtension
    tags:
      - { name: twig.extension }
  pm.twig.flag:
    class: PM\Bundle\ToolBundle\Twig\FlagExtension
    tags:
      - { name: twig.extension }
  pm.twig.country:
    class: PM\Bundle\ToolBundle\Twig\CountryExtension
    tags:
      - { name: twig.extension }
      
  pm.knpmenu.voter:
    class: PM\Bundle\ToolBundle\KnpMenu\RouteVoter
    arguments: ["@service_container"]
    tags:
      - { name: knp_menu.voter }
      
  pm.pdf:
    class: PM\Bundle\ToolBundle\Services\PdfService
    arguments: ["%kernel.root_dir%"]



