imports:
    - { resource: "services/google.yml" }
    - { resource: "services/listener.yml" }
    - { resource: "services/twig.yml" }

services:
    pm.knpmenu.voter:
        class: PM\Bundle\ToolBundle\KnpMenu\RouteVoter
        arguments: ["@request_stack"]
        tags:
          - { name: knp_menu.voter }

    pm.pdf:
        class: PM\Bundle\ToolBundle\Services\PdfService
        public: true
        arguments: ["%kernel.root_dir%"]

    pm.image:
        class: PM\Bundle\ToolBundle\Services\ImageService
        public: true

    pm.cronjob:
        class: PM\Bundle\ToolBundle\Services\CronjobService
        public: true
        calls:
            - [setLogger, ['@logger']]
            - [setEventDispatcher, ['@event_dispatcher']]

    PM\Bundle\ToolBundle\Services\ResponseService:
        arguments: ['@translator', '@router.default', '@session']