services:
  pm.twig.cssversion:
    class: PM\Bundle\ToolBundle\Twig\CssVersionExtension
    arguments: ["%kernel.root_dir%"]
    tags:
      - { name: twig.extension }

  pm.twig.hash:
    class: PM\Bundle\ToolBundle\Twig\HashExtension
    tags:
      - { name: twig.extension }

  pm.twig.icon:
    class: PM\Bundle\ToolBundle\Twig\IconExtension
    tags:
      - { name: twig.extension }

  pm.twig.flag:
    class: PM\Bundle\ToolBundle\Twig\FlagExtension
    tags:
      - { name: twig.extension }

  pm.twig.fos_user:
    class: PM\Bundle\ToolBundle\Twig\FOSUserExtension
    calls:
        - [setDoctrine, ['@doctrine']]
    tags:
        - { name: twig.extension }

  pm.twig.country:
    class: PM\Bundle\ToolBundle\Twig\CountryExtension
    tags:
      - { name: twig.extension }

  pm.twig.seo:
      class: PM\Bundle\ToolBundle\Twig\SeoExtension
      tags:
        - { name: twig.extension }

  pm.twig.time:
      class: PM\Bundle\ToolBundle\Twig\TimeExtension
      tags:
        - { name: twig.extension }

  pm.twig.json:
    class: PM\Bundle\ToolBundle\Twig\JsonExtension
    tags:
        - { name: twig.extension }